// StudentsData.js
export const initialStudentsData = [
  {
    key: "1",
    id: 1,
    studentId: 1,
    name: "Juan",
    paternalLastName: "Pérez",
    maternalLastName: "García",
    email: "juanp@example.com",
    phone: "9991234567",
    status: "Suspendido",
    registrationDate: "2024-03-12",
    university: "UADY",
    documents: [
      {
        id: 1,
        studentId: 1,
        documentType: "INE",
        fileName: "ine.pdf",
        fileSize: "2.4 MB",
        path: "/documents/student_1/ine.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-03-10",
        reviewDate: "2024-03-11",
        reviewedBy: "Admin Principal",
      },
      {
        id: 2,
        studentId: 1,
        documentType: "Comprobante de domicilio",
        fileName: "comprobante_domicilio.pdf",
        fileSize: "1.8 MB",
        path: "/documents/student_1/comprobante.pdf",
        status: "Rechazado",
        rejectionReasons: "Documento ilegible, fecha mayor a 3 meses",
        uploadDate: "2024-03-10",
        reviewDate: "2024-03-12",
        reviewedBy: "Admin Secundario",
      },
    ],
  },
  {
    key: "2",
    id: 2,
    studentId: 2,
    name: "Carlos",
    paternalLastName: "Méndez",
    maternalLastName: "Ortega",
    email: "carlos.mendez@example.com",
    phone: "5567892345",
    status: "Activo",
    registrationDate: "2024-05-20",
    university: "UADY",
    documents: [
      {
        id: 3,
        studentId: 2,
        documentType: "INE",
        fileName: "ine_carlos.pdf",
        fileSize: "3.1 MB",
        path: "/documents/student_2/ine.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-05-18",
        reviewDate: "2024-05-19",
        reviewedBy: "Admin Principal",
      },
      {
        id: 4,
        studentId: 2,
        documentType: "Credencial universitaria",
        fileName: "credencial_uady.pdf",
        fileSize: "1.2 MB",
        path: "/documents/student_2/credencial.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-05-18",
        reviewDate: "2024-05-19",
        reviewedBy: "Admin Principal",
      },
      {
        id: 5,
        studentId: 2,
        documentType: "Comprobante de domicilio",
        fileName: "comprobante_cfe.pdf",
        fileSize: "2.0 MB",
        path: "/documents/student_2/comprobante.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-05-18",
        reviewDate: "2024-05-20",
        reviewedBy: "Admin Secundario",
      },
    ],
  },
  {
    key: "3",
    id: 3,
    studentId: 3,
    name: "Ricardo",
    paternalLastName: "Herrera",
    maternalLastName: "Torres",
    email: "ricardo.h@gmail.com",
    phone: "3312349988",
    status: "Activo",
    registrationDate: "2024-02-02",
    university: "UADY",
    documents: [
      {
        id: 6,
        studentId: 3,
        documentType: "INE",
        fileName: "identificacion.pdf",
        fileSize: "2.8 MB",
        path: "/documents/student_3/ine.pdf",
        status: "Pendiente",
        rejectionReasons: null,
        uploadDate: "2024-02-01",
        reviewDate: null,
        reviewedBy: null,
      },
    ],
  },
  {
    key: "4",
    id: 4,
    studentId: 4,
    name: "María",
    paternalLastName: "García",
    maternalLastName: "Pérez",
    email: "maria.garcia@example.com",
    phone: "9998765432",
    status: "Activo",
    registrationDate: "2024-01-15",
    university: "UADY",
    documents: [
      {
        id: 7,
        studentId: 4,
        documentType: "INE",
        fileName: "ine_maria.pdf",
        fileSize: "2.5 MB",
        path: "/documents/student_4/ine.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-01-13",
        reviewDate: "2024-01-14",
        reviewedBy: "Admin Principal",
      },
      {
        id: 8,
        studentId: 4,
        documentType: "Comprobante de domicilio",
        fileName: "comprobante_agua.pdf",
        fileSize: "1.5 MB",
        path: "/documents/student_4/comprobante.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-01-13",
        reviewDate: "2024-01-14",
        reviewedBy: "Admin Principal",
      },
      {
        id: 9,
        studentId: 4,
        documentType: "Credencial universitaria",
        fileName: "credencial.pdf",
        fileSize: "1.1 MB",
        path: "/documents/student_4/credencial.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-01-13",
        reviewDate: "2024-01-15",
        reviewedBy: "Admin Secundario",
      },
    ],
  },
  {
    key: "5",
    id: 5,
    studentId: 5,
    name: "Juan",
    paternalLastName: "Ramírez",
    maternalLastName: "López",
    email: "juan.ramirez@example.com",
    phone: "5551234567",
    status: "Activo",
    registrationDate: "2024-06-10",
    university: "UADY",
    documents: [],
  },
  {
    key: "6",
    id: 6,
    studentId: 6,
    name: "Ana",
    paternalLastName: "Martínez",
    maternalLastName: "Sánchez",
    email: "ana.martinez@example.com",
    phone: "9993456789",
    status: "Activo",
    registrationDate: "2024-04-18",
    university: "UNAM",
    documents: [
      {
        id: 10,
        studentId: 6,
        documentType: "INE",
        fileName: "ine_ana.pdf",
        fileSize: "2.7 MB",
        path: "/documents/student_6/ine.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-04-16",
        reviewDate: "2024-04-17",
        reviewedBy: "Admin Principal",
      },
      {
        id: 11,
        studentId: 6,
        documentType: "Comprobante de domicilio",
        fileName: "comprobante_antiguo.pdf",
        fileSize: "1.9 MB",
        path: "/documents/student_6/comprobante.pdf",
        status: "Rechazado",
        rejectionReasons: "Documento con más de 3 meses de antigüedad",
        uploadDate: "2024-04-16",
        reviewDate: "2024-04-18",
        reviewedBy: "Admin Secundario",
      },
    ],
  },
  {
    key: "7",
    id: 7,
    studentId: 7,
    name: "Luis",
    paternalLastName: "González",
    maternalLastName: "Fernández",
    email: "luis.gonzalez@example.com",
    phone: "5556781234",
    status: "Suspendido",
    registrationDate: "2024-03-25",
    university: "UTR",
    documents: [
      {
        id: 12,
        studentId: 7,
        documentType: "INE",
        fileName: "ine_vencida.pdf",
        fileSize: "2.3 MB",
        path: "/documents/student_7/ine.pdf",
        status: "Rechazado",
        rejectionReasons: "Documento vencido",
        uploadDate: "2024-03-23",
        reviewDate: "2024-03-24",
        reviewedBy: "Admin Principal",
      },
    ],
  },
  {
    key: "8",
    id: 8,
    studentId: 8,
    name: "Sofía",
    paternalLastName: "López",
    maternalLastName: "Hernández",
    email: "sofia.lopez@example.com",
    phone: "9994567890",
    status: "Activo",
    registrationDate: "2024-05-05",
    university: "UTR",
    documents: [
      {
        id: 13,
        studentId: 8,
        documentType: "INE",
        fileName: "ine_sofia.pdf",
        fileSize: "2.6 MB",
        path: "/documents/student_8/ine.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-05-03",
        reviewDate: "2024-05-04",
        reviewedBy: "Admin Principal",
      },
      {
        id: 14,
        studentId: 8,
        documentType: "Credencial universitaria",
        fileName: "credencial_utr.pdf",
        fileSize: "1.4 MB",
        path: "/documents/student_8/credencial.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-05-03",
        reviewDate: "2024-05-04",
        reviewedBy: "Admin Principal",
      },
    ],
  },
  {
    key: "9",
    id: 9,
    studentId: 9,
    name: "Diego",
    paternalLastName: "Rodríguez",
    maternalLastName: "Morales",
    email: "diego.rodriguez@example.com",
    phone: "3319876543",
    status: "Activo",
    registrationDate: "2024-01-30",
    university: "UADY",
    documents: [
      {
        id: 15,
        studentId: 9,
        documentType: "INE",
        fileName: "ine_diego.pdf",
        fileSize: "2.9 MB",
        path: "/documents/student_9/ine.pdf",
        status: "Pendiente",
        rejectionReasons: null,
        uploadDate: "2024-01-28",
        reviewDate: null,
        reviewedBy: null,
      },
      {
        id: 16,
        studentId: 9,
        documentType: "Comprobante de domicilio",
        fileName: "comprobante_luz.pdf",
        fileSize: "1.7 MB",
        path: "/documents/student_9/comprobante.pdf",
        status: "Pendiente",
        rejectionReasons: null,
        uploadDate: "2024-01-28",
        reviewDate: null,
        reviewedBy: null,
      },
    ],
  },
  {
    key: "10",
    id: 10,
    studentId: 10,
    name: "Valentina",
    paternalLastName: "Torres",
    maternalLastName: "Ruiz",
    email: "valentina.torres@example.com",
    phone: "5558765432",
    status: "Activo",
    registrationDate: "2024-02-14",
    university: "UNAM",
    documents: [
      {
        id: 17,
        studentId: 10,
        documentType: "INE",
        fileName: "ine_valentina.pdf",
        fileSize: "2.8 MB",
        path: "/documents/student_10/ine.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-02-12",
        reviewDate: "2024-02-13",
        reviewedBy: "Admin Principal",
      },
      {
        id: 18,
        studentId: 10,
        documentType: "Comprobante de domicilio",
        fileName: "comprobante_internet.pdf",
        fileSize: "1.6 MB",
        path: "/documents/student_10/comprobante.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-02-12",
        reviewDate: "2024-02-13",
        reviewedBy: "Admin Principal",
      },
      {
        id: 19,
        studentId: 10,
        documentType: "Credencial universitaria",
        fileName: "credencial_unam.pdf",
        fileSize: "1.3 MB",
        path: "/documents/student_10/credencial.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-02-12",
        reviewDate: "2024-02-13",
        reviewedBy: "Admin Secundario",
      },
      {
        id: 20,
        studentId: 10,
        documentType: "Constancia de estudios",
        fileName: "constancia_estudios.pdf",
        fileSize: "1.9 MB",
        path: "/documents/student_10/constancia.pdf",
        status: "Aprobado",
        rejectionReasons: null,
        uploadDate: "2024-02-12",
        reviewDate: "2024-02-14",
        reviewedBy: "Admin Secundario",
      },
    ],
  },
];