export const initialOwnersData = [
  {
    key: "1",
    id: 1,
    name: "Ana López",
    email: "ana.lopez@example.com",
    phone: "9991234567",
    status: "Suspendido",
    registrationDate: "2024-03-12",
    properties: 0,
  },
  {
    key: "2",
    id: 2,
    name: "Carlos Méndez Ortega",
    email: "carlos.mendez@example.com",
    phone: "5567892345",
    status: "Verificado",
    registrationDate: "2024-05-20",
    properties: 3,
  },
  {
    key: "3",
    id: 3,
    name: "Ricardo Herrera Torres",
    email: "ricardo.h@gmail.com",
    phone: "3312349988",
    status: "Pendiente",
    registrationDate: "2024-02-02",
    properties: 1,
  },
  {
    key: "4",
    id: 4,
    name: "María García Pérez",
    email: "maria.garcia@example.com",
    phone: "9998765432",
    status: "Verificado",
    registrationDate: "2024-01-15",
    properties: 2,
  },
  {
    key: "5",
    id: 5,
    name: "Juan Ramírez López",
    email: "juan.ramirez@example.com",
    phone: "5551234567",
    status: "Pendiente",
    registrationDate: "2024-06-10",
    properties: 0,
  },
];
