export const initialOwnersData = [
  {
    key: "1",
    id: 1,
    name: "Ana López",
    email: "ana.lopez@example.com",
    phone: "9991234567",
    status: "Suspendido",
    registrationDate: "2024-03-12",
    properties: 0,
  },
  {
    key: "2",
    id: 2,
    name: "Carlos Méndez Ortega",
    email: "carlos.mendez@example.com",
    phone: "5567892345",
    status: "Verificado",
    registrationDate: "2024-05-20",
    properties: 3,
  },
  {
    key: "3",
    id: 3,
    name: "Ricardo Herrera Torres",
    email: "ricardo.h@gmail.com",
    phone: "3312349988",
    status: "Pendiente",
    registrationDate: "2024-02-02",
    properties: 1,
  },
  {
    key: "4",
    id: 4,
    name: "María García Pérez",
    email: "maria.garcia@example.com",
    phone: "9998765432",
    status: "Verificado",
    registrationDate: "2024-01-15",
    properties: 2,
  },
  {
    key: "5",
    id: 5,
    name: "Juan Ramírez López",
    email: "juan.ramirez@example.com",
    phone: "5551234567",
    status: "Pendiente",
    registrationDate: "2024-06-10",
    properties: 0,
  },
];

// Datos de propiedades asociadas a propietarios
export const initialPropertiesData = [
  {
    key: "1",
    id: 1,
    ownerId: 2,
    propertyName: "Casa Colonial Centro",
    image: "https://images.adsttc.com/media/images/5eb2/bb00/b357/65f8/f900/0274/large_jpg/RoryGardiner1161c_Set-1_005.jpg?1588771572",
    address: "Calle 45 #123, Col. Centro",
    city: "Mérida",
    state: "Yucatán",
    zipCode: "97000",
    propertyType: "Casa",
    rentalType: "Completa",
    priceFrom: 15000,
    status: "Activo",
    registrationDate: "2024-05-21",
    description: "Hermosa casa colonial en el centro histórico de Mérida",
  },
  {
    key: "2",
    id: 2,
    ownerId: 2,
    propertyName: "Departamento García Ginerés",
    image: "https://yucatantoday.com/hubfs/Imported_Blog_Media/palacio-canton-destacada-casas-iconicas-de-merida-1.jpg",
    address: "Av. Colón #456, Col. García Ginerés",
    city: "Mérida",
    state: "Yucatán",
    zipCode: "97070",
    propertyType: "Departamento",
    rentalType: "Por espacios",
    priceFrom: 8000,
    status: "Activo",
    registrationDate: "2024-06-15",
    description: "Departamento moderno con excelente ubicación",
  },
  {
    key: "3",
    id: 3,
    ownerId: 2,
    propertyName: "Local Comercial Centro",
    image: "https://media.admagazine.com/photos/63eefdf8e8f181938140d132/4:3/w_907,h_680,c_limit/Casa%20%20Pakaal,%20Workshop%2001.jpg",
    address: "Calle 60 #789, Col. Centro",
    city: "Mérida",
    state: "Yucatán",
    zipCode: "97000",
    propertyType: "Local Comercial",
    rentalType: "Completa",
    priceFrom: 25000,
    status: "Inactivo",
    registrationDate: "2024-07-10",
    description: "Amplio local comercial en zona de alto tráfico",
  },
  {
    key: "4",
    id: 4,
    ownerId: 3,
    propertyName: "Villa Jardines",
    image: "https://realestateyucatan.com/files/media/image/raw_2eba25ac379d770f92a6befbf4cc7279.jpg",
    address: "Calle 23 #321, Col. Jardines",
    city: "Cancún",
    state: "Quintana Roo",
    zipCode: "77500",
    propertyType: "Casa",
    rentalType: "Completa",
    priceFrom: 20000,
    status: "Activo",
    registrationDate: "2024-02-15",
    description: "Villa espaciosa cerca de la playa",
  },
  {
    key: "5",
    id: 5,
    ownerId: 4,
    propertyName: "Residencia Itzimná",
    image: "https://img.trovit.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci9iMjQ2MjZhMC1iYjdkLTNiOWYtODE2ZS03ZGE0ZGEzZjM3NWIvMzExYzhiZmNkOWQ2NDU5M2QyZWEwOTlhNTRjNjZmNzk1YjliMzVhNmIzN2VjMzUyYzEyOTcxMTYyY2FmYjlkZC5qcGVnIiwiYnJhbmQiOiJ0cm92aXQiLCJlZGl0cyI6eyJyb3RhdGUiOm51bGwsInJlc2l6ZSI6eyJ3aWR0aCI6MzYwLCJoZWlnaHQiOjI3MCwiZml0IjoiY292ZXIifX19",
    address: "Av. Reforma #111, Col. Itzimná",
    city: "Mérida",
    state: "Yucatán",
    zipCode: "97100",
    propertyType: "Casa",
    rentalType: "Por espacios",
    priceFrom: 6000,
    status: "Activo",
    registrationDate: "2024-01-20",
    description: "Casa grande ideal para estudiantes o profesionistas",
  },
  {
    key: "6",
    id: 6,
    ownerId: 4,
    propertyName: "Penthouse Montejo",
    image: "https://plalla.com/wp-content/uploads/2025/01/alberca-privada-adara-merida.webp",
    address: "Prolongación Montejo #222, Col. Montejo",
    city: "Mérida",
    state: "Yucatán",
    zipCode: "97115",
    propertyType: "Departamento",
    rentalType: "Completa",
    priceFrom: 35000,
    status: "Activo",
    registrationDate: "2024-03-05",
    description: "Lujoso penthouse con vista panorámica",
  },
];