export const initialOwnersData = [
  {
    key: "1",
    id: 1,
    name: "Ana López",
    email: "ana.lopez@example.com",
    phone: "9991234567",
    status: "Suspendido",
    registrationDate: "2024-03-12",
    properties: 0,
  },
  {
    key: "2",
    id: 2,
    name: "Carlos Méndez Ortega",
    email: "carlos.mendez@example.com",
    phone: "5567892345",
    status: "Verificado",
    registrationDate: "2024-05-20",
    properties: 3,
  },
  {
    key: "3",
    id: 3,
    name: "Ricardo Herrera Torres",
    email: "ricardo.h@gmail.com",
    phone: "3312349988",
    status: "Pendiente",
    registrationDate: "2024-02-02",
    properties: 1,
  },
  {
    key: "4",
    id: 4,
    name: "María García Pérez",
    email: "maria.garcia@example.com",
    phone: "9998765432",
    status: "Verificado",
    registrationDate: "2024-01-15",
    properties: 2,
  },
  {
    key: "5",
    id: 5,
    name: "Juan Ramírez López",
    email: "juan.ramirez@example.com",
    phone: "5551234567",
    status: "Pendiente",
    registrationDate: "2024-06-10",
    properties: 0,
  },
];

// Datos de propiedades asociadas a propietarios
export const initialPropertiesData = [
  {
    key: "1",
    id: 1,
    ownerId: 2,
    propertyName: "Casa Colonial Centro",
    image: "https://images.adsttc.com/media/images/5eb2/bb00/b357/65f8/f900/0274/large_jpg/RoryGardiner1161c_Set-1_005.jpg?1588771572",
    address: "Calle 45 #123, Col. Centro",
    city: "Mérida",
    state: "Yucatán",
    zipCode: "97000",
    propertyType: "Casa",
    rentalType: "Completa",
    priceFrom: 15000,
    status: "Activo",
    registrationDate: "2024-05-21",
    description: "Hermosa casa colonial en el centro histórico de Mérida",
    services: [
      {
        key: "1",
        id: 1,
        serviceType: "water",
        serviceName: "Agua",
        monthlyPrice: 300,
        icon: "water",
      },
      {
        key: "2",
        id: 2,
        serviceType: "electricity",
        serviceName: "Luz",
        monthlyPrice: 800,
        icon: "electricity",
      },
      {
        key: "3",
        id: 3,
        serviceType: "internet",
        serviceName: "Internet",
        monthlyPrice: 500,
        icon: "internet",
      },
      {
        key: "4",
        id: 4,
        serviceType: "gas",
        serviceName: "Gas",
        monthlyPrice: 400,
        icon: "gas",
      },
    ],
  },
  {
    key: "2",
    id: 2,
    ownerId: 2,
    propertyName: "Departamento García Ginerés",
    image: "https://yucatantoday.com/hubfs/Imported_Blog_Media/palacio-canton-destacada-casas-iconicas-de-merida-1.jpg",
    address: "Av. Colón #456, Col. García Ginerés",
    city: "Mérida",
    state: "Yucatán",
    zipCode: "97070",
    propertyType: "Departamento",
    rentalType: "Por espacios",
    priceFrom: 8000,
    status: "Activo",
    registrationDate: "2024-06-15",
    description: "Departamento moderno con excelente ubicación",
    spaces: [
      {
        key: "1",
        id: 1,
        spaceName: "Habitación Principal",
        spaceNumber: "101",
        monthlyPrice: 8000,
        beds: [
          {
            key: "1",
            id: 1,
            bedName: "Cama King",
            bedNumber: "K-1",
            monthlyPrice: 4000,
          },
          {
            key: "2",
            id: 2,
            bedName: "Cama Individual",
            bedNumber: "I-1",
            monthlyPrice: 3000,
          },
          {
            key: "3",
            id: 3,
            bedName: "Sofá cama",
            bedNumber: "S-1",
            monthlyPrice: 2500,
          },
        ],
      },
      {
        key: "2",
        id: 2,
        spaceName: "Habitación Secundaria",
        spaceNumber: "102",
        monthlyPrice: 6500,
        beds: [
          {
            key: "1",
            id: 1,
            bedName: "Cama Queen",
            bedNumber: "Q-1",
            monthlyPrice: 3500,
          },
          {
            key: "2",
            id: 2,
            bedName: "Cama Individual",
            bedNumber: "I-2",
            monthlyPrice: 2800,
          },
        ],
      },
      {
        key: "3",
        id: 3,
        spaceName: "Estudio",
        spaceNumber: "103",
        monthlyPrice: 5500,
        beds: [],
      },
      {
        key: "4",
        id: 4,
        spaceName: "Habitación Compartida",
        spaceNumber: "104",
        monthlyPrice: 7000,
        beds: [
          {
            key: "1",
            id: 1,
            bedName: "Litera Superior",
            bedNumber: "LS-1",
            monthlyPrice: 2200,
          },
          {
            key: "2",
            id: 2,
            bedName: "Litera Inferior",
            bedNumber: "LI-1",
            monthlyPrice: 2400,
          },
          {
            key: "3",
            id: 3,
            bedName: "Cama Individual",
            bedNumber: "I-3",
            monthlyPrice: 2500,
          },
        ],
      },
    ],
    services: [
      {
        key: "1",
        id: 1,
        serviceType: "water",
        serviceName: "Agua",
        monthlyPrice: 200,
        icon: "water",
      },
      {
        key: "2",
        id: 2,
        serviceType: "electricity",
        serviceName: "Luz",
        monthlyPrice: 500,
        icon: "electricity",
      },
      {
        key: "3",
        id: 3,
        serviceType: "internet",
        serviceName: "Internet de alta velocidad",
        monthlyPrice: 600,
        icon: "internet",
      },
      {
        key: "4",
        id: 4,
        serviceType: "maintenance",
        serviceName: "Mantenimiento",
        monthlyPrice: 350,
        icon: "maintenance",
      },
    ],
  },
  {
    key: "3",
    id: 3,
    ownerId: 2,
    propertyName: "Local Comercial Centro",
    image: "https://media.admagazine.com/photos/63eefdf8e8f181938140d132/4:3/w_907,h_680,c_limit/Casa%20%20Pakaal,%20Workshop%2001.jpg",
    address: "Calle 60 #789, Col. Centro",
    city: "Mérida",
    state: "Yucatán",
    zipCode: "97000",
    propertyType: "Local Comercial",
    rentalType: "Completa",
    priceFrom: 25000,
    status: "Inactivo",
    registrationDate: "2024-07-10",
    description: "Amplio local comercial en zona de alto tráfico",
    services: [
      {
        key: "1",
        id: 1,
        serviceType: "water",
        serviceName: "Agua",
        monthlyPrice: 500,
        icon: "water",
      },
      {
        key: "2",
        id: 2,
        serviceType: "electricity",
        serviceName: "Luz trifásica",
        monthlyPrice: 2000,
        icon: "electricity",
      },
      {
        key: "3",
        id: 3,
        serviceType: "internet",
        serviceName: "Internet empresarial",
        monthlyPrice: 1200,
        icon: "internet",
      },
    ],
  },
  {
    key: "4",
    id: 4,
    ownerId: 3,
    propertyName: "Villa Jardines",
    image: "https://realestateyucatan.com/files/media/image/raw_2eba25ac379d770f92a6befbf4cc7279.jpg",
    address: "Calle 23 #321, Col. Jardines",
    city: "Cancún",
    state: "Quintana Roo",
    zipCode: "77500",
    propertyType: "Casa",
    rentalType: "Completa",
    priceFrom: 20000,
    status: "Activo",
    registrationDate: "2024-02-15",
    description: "Villa espaciosa cerca de la playa",
    services: [
      {
        key: "1",
        id: 1,
        serviceType: "water",
        serviceName: "Agua",
        monthlyPrice: 400,
        icon: "water",
      },
      {
        key: "2",
        id: 2,
        serviceType: "electricity",
        serviceName: "Luz",
        monthlyPrice: 1200,
        icon: "electricity",
      },
      {
        key: "3",
        id: 3,
        serviceType: "internet",
        serviceName: "Internet",
        monthlyPrice: 700,
        icon: "internet",
      },
      {
        key: "4",
        id: 4,
        serviceType: "gas",
        serviceName: "Gas",
        monthlyPrice: 500,
        icon: "gas",
      },
      {
        key: "5",
        id: 5,
        serviceType: "gardening",
        serviceName: "Jardinería",
        monthlyPrice: 800,
        icon: "gardening",
      },
    ],
  },
  {
    key: "5",
    id: 5,
    ownerId: 4,
    propertyName: "Residencia Itzimná",
    image: "https://img.trovit.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci9iMjQ2MjZhMC1iYjdkLTNiOWYtODE2ZS03ZGE0ZGEzZjM3NWIvMzExYzhiZmNkOWQ2NDU5M2QyZWEwOTlhNTRjNjZmNzk1YjliMzVhNmIzN2VjMzUyYzEyOTcxMTYyY2FmYjlkZC5qcGVnIiwiYnJhbmQiOiJ0cm92aXQiLCJlZGl0cyI6eyJyb3RhdGUiOm51bGwsInJlc2l6ZSI6eyJ3aWR0aCI6MzYwLCJoZWlnaHQiOjI3MCwiZml0IjoiY292ZXIifX19",
    address: "Av. Reforma #111, Col. Itzimná",
    city: "Mérida",
    state: "Yucatán",
    zipCode: "97100",
    propertyType: "Casa",
    rentalType: "Por espacios",
    priceFrom: 6000,
    status: "Activo",
    registrationDate: "2024-01-20",
    description: "Casa grande ideal para estudiantes o profesionistas",
    spaces: [
      {
        key: "1",
        id: 1,
        spaceName: "Cuarto 1",
        spaceNumber: "A-1",
        monthlyPrice: 6000,
        beds: [
          {
            key: "1",
            id: 1,
            bedName: "Cama Matrimonial",
            bedNumber: "M-1",
            monthlyPrice: 3000,
          },
          {
            key: "2",
            id: 2,
            bedName: "Cama Individual",
            bedNumber: "I-1",
            monthlyPrice: 2500,
          },
        ],
      },
      {
        key: "2",
        id: 2,
        spaceName: "Cuarto 2",
        spaceNumber: "A-2",
        monthlyPrice: 6000,
        beds: [
          {
            key: "1",
            id: 1,
            bedName: "Cama Queen",
            bedNumber: "Q-1",
            monthlyPrice: 3200,
          },
          {
            key: "2",
            id: 2,
            bedName: "Cama Individual",
            bedNumber: "I-2",
            monthlyPrice: 2600,
          },
        ],
      },
      {
        key: "3",
        id: 3,
        spaceName: "Cuarto 3",
        spaceNumber: "A-3",
        monthlyPrice: 5500,
        beds: [
          {
            key: "1",
            id: 1,
            bedName: "Litera Superior",
            bedNumber: "LS-1",
            monthlyPrice: 2800,
          },
          {
            key: "2",
            id: 2,
            bedName: "Litera Inferior",
            bedNumber: "LI-1",
            monthlyPrice: 2800,
          },
        ],
      },
      {
        key: "4",
        id: 4,
        spaceName: "Cuarto 4",
        spaceNumber: "B-1",
        monthlyPrice: 5500,
        beds: [
          {
            key: "1",
            id: 1,
            bedName: "Cama Matrimonial",
            bedNumber: "M-2",
            monthlyPrice: 2900,
          },
          {
            key: "2",
            id: 2,
            bedName: "Cama Individual",
            bedNumber: "I-3",
            monthlyPrice: 2400,
          },
        ],
      },
      {
        key: "5",
        id: 5,
        spaceName: "Cuarto 5",
        spaceNumber: "B-2",
        monthlyPrice: 5000,
        beds: [
          {
            key: "1",
            id: 1,
            bedName: "Cama Individual",
            bedNumber: "I-4",
            monthlyPrice: 2500,
          },
          {
            key: "2",
            id: 2,
            bedName: "Cama Individual",
            bedNumber: "I-5",
            monthlyPrice: 2500,
          },
        ],
      },
      {
        key: "6",
        id: 6,
        spaceName: "Cuarto 6",
        spaceNumber: "B-3",
        monthlyPrice: 7500,
        beds: [
          {
            key: "1",
            id: 1,
            bedName: "Cama King",
            bedNumber: "K-1",
            monthlyPrice: 4000,
          },
          {
            key: "2",
            id: 2,
            bedName: "Litera Superior",
            bedNumber: "LS-2",
            monthlyPrice: 1800,
          },
          {
            key: "3",
            id: 3,
            bedName: "Litera Inferior",
            bedNumber: "LI-2",
            monthlyPrice: 1800,
          },
        ],
      },
    ],
    services: [
      {
        key: "1",
        id: 1,
        serviceType: "water",
        serviceName: "Agua",
        monthlyPrice: 250,
        icon: "water",
      },
      {
        key: "2",
        id: 2,
        serviceType: "electricity",
        serviceName: "Luz",
        monthlyPrice: 600,
        icon: "electricity",
      },
      {
        key: "3",
        id: 3,
        serviceType: "internet",
        serviceName: "Internet",
        monthlyPrice: 450,
        icon: "internet",
      },
      {
        key: "4",
        id: 4,
        serviceType: "gas",
        serviceName: "Gas",
        monthlyPrice: 300,
        icon: "gas",
      },
      {
        key: "5",
        id: 5,
        serviceType: "cleaning",
        serviceName: "Limpieza común",
        monthlyPrice: 200,
        icon: "cleaning",
      },
    ],
  },
  {
    key: "6",
    id: 6,
    ownerId: 4,
    propertyName: "Penthouse Montejo",
    image: "https://plalla.com/wp-content/uploads/2025/01/alberca-privada-adara-merida.webp",
    address: "Prolongación Montejo #222, Col. Montejo",
    city: "Mérida",
    state: "Yucatán",
    zipCode: "97115",
    propertyType: "Departamento",
    rentalType: "Completa",
    priceFrom: 35000,
    status: "Activo",
    registrationDate: "2024-03-05",
    description: "Lujoso penthouse con vista panorámica",
    services: [
      {
        key: "1",
        id: 1,
        serviceType: "water",
        serviceName: "Agua",
        monthlyPrice: 400,
        icon: "water",
      },
      {
        key: "2",
        id: 2,
        serviceType: "electricity",
        serviceName: "Luz",
        monthlyPrice: 1500,
        icon: "electricity",
      },
      {
        key: "3",
        id: 3,
        serviceType: "internet",
        serviceName: "Internet premium",
        monthlyPrice: 900,
        icon: "internet",
      },
      {
        key: "4",
        id: 4,
        serviceType: "gas",
        serviceName: "Gas",
        monthlyPrice: 600,
        icon: "gas",
      },
      {
        key: "5",
        id: 5,
        serviceType: "maintenance",
        serviceName: "Mantenimiento premium",
        monthlyPrice: 1200,
        icon: "maintenance",
      },
      {
        key: "6",
        id: 6,
        serviceType: "security",
        serviceName: "Seguridad 24/7",
        monthlyPrice: 800,
        icon: "security",
      },
      {
        key: "7",
        id: 7,
        serviceType: "amenities",
        serviceName: "Uso de amenidades",
        monthlyPrice: 1000,
        icon: "amenities",
      },
    ],
  },
];